name: ci
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
jobs:
  test-grant-legacy-role:
    runs-on: ubuntu-latest
    env:
      BATON_LOG_LEVEL: debug
      BATON_WORKATO_API_KEY: ${{ secrets.BATON_WORKATO_API_KEY }}
      BATON_WORKATO_DATA_CENTER: sandbox
      BATON_WORKATO_ENV: dev
      BATON_DISABLE_CUSTOM_ROLES_SYNC: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Install baton
        run: ./scripts/get-baton.sh && mv baton /usr/local/bin
      - name: Build baton-workato
        run: go build ./cmd/baton-workato
      - name: Sync
        run: ./baton-workato
      - name: Grant Operator role
        run: ./baton-workato --grant-entitlement="role:Operator:collaborator-has" --grant-principal="${{ secrets.CONNECTOR_PRINCIPAL }}" --grant-principal-type="collaborator"
      - name: Grant Operator role again (idempotency)
        run: ./baton-workato --grant-entitlement="role:Operator:collaborator-has" --grant-principal="${{ secrets.CONNECTOR_PRINCIPAL }}" --grant-principal-type="collaborator"
      - name: Sync and verify grant
        run: |
          ./baton-workato
          baton grants --entitlement="role:Operator:collaborator-has" | grep "${{ secrets.CONNECTOR_PRINCIPAL }}"

  test-grant-environment-role:
    runs-on: ubuntu-latest
    env:
      BATON_LOG_LEVEL: debug
      BATON_WORKATO_API_KEY: ${{ secrets.BATON_WORKATO_API_KEY }}
      BATON_WORKATO_DATA_CENTER: sandbox
      BATON_WORKATO_ENV: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Install baton
        run: ./scripts/get-baton.sh && mv baton /usr/local/bin
      - name: Build baton-workato
        run: go build ./cmd/baton-workato
      - name: Sync
        run: ./baton-workato
      - name: Grant environment role
        run: ./baton-workato --grant-entitlement="${{ vars.BATON_ENTITLEMENT_ENV_ROLE }}" --grant-principal="${{ secrets.CONNECTOR_PRINCIPAL }}" --grant-principal-type="collaborator"
      - name: Grant environment role again (idempotency)
        run: ./baton-workato --grant-entitlement="${{ vars.BATON_ENTITLEMENT_ENV_ROLE }}" --grant-principal="${{ secrets.CONNECTOR_PRINCIPAL }}" --grant-principal-type="collaborator"
      - name: Sync and verify grant
        run: |
          ./baton-workato
          baton grants --entitlement="${{ vars.BATON_ENTITLEMENT_ENV_ROLE }}" | grep "${{ secrets.CONNECTOR_PRINCIPAL }}"
