name: ci
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
jobs:
  test-provisioning:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        test-case: [roles]
    env:
      BATON_LOG_LEVEL: debug
      CONNECTOR_PRINCIPAL: "${{ secrets.CONNECTOR_PRINCIPAL }}"
      BATON_WORKATO_API_KEY: ${{ secrets.BATON_WORKATO_API_KEY }}
      BATON_CONNECTOR: ./baton-workato
      BATON_WORKATO_ENV: dev
      BATON_DISABLE_CUSTOM_ROLES_SYNC: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Install baton
        run: ./scripts/get-baton.sh && mv baton /usr/local/bin
      - name: Build baton-workato
        run: go build ./cmd/baton-workato
      - name: Run tests for ${{ matrix.test-case }}
        run: |-
          case "${{ matrix.test-case }}" in
            "roles")
              BATON_SKIP_REVOKE=1 ./scripts/validate-grant.sh ${{ env.CONNECTOR_PRINCIPAL }} collaborator role:Operator:collaborator-has role:Operator:collaborator-has:collaborator:${{ env.CONNECTOR_PRINCIPAL }}
              ;;
          esac
